// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoxLoader: typeof import('./src/components/BoxLoader.vue')['default']
    Check: typeof import('./src/components/icons/home/check.vue')['default']
    Date: typeof import('./src/components/icons/home/date.vue')['default']
    Edit: typeof import('./src/components/icons/home/edit.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GeeTest: typeof import('./src/components/captcha/GeeTest.vue')['default']
    General: typeof import('./src/components/icons/home/general.vue')['default']
    Gift: typeof import('./src/components/icons/home/gift.vue')['default']
    Gitee: typeof import('./src/components/icons/gitee.vue')['default']
    Github: typeof import('./src/components/icons/github.vue')['default']
    Google: typeof import('./src/components/icons/google.vue')['default']
    Home: typeof import('./src/components/icons/home.vue')['default']
    Key: typeof import('./src/components/icons/home/key.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Login: typeof import('./src/components/icons/login.vue')['default']
    Mail: typeof import('./src/components/icons/home/mail.vue')['default']
    Money: typeof import('./src/components/icons/home/money.vue')['default']
    Name: typeof import('./src/components/icons/home/name.vue')['default']
    Oauth: typeof import('./src/components/icons/home/oauth.vue')['default']
    Olink: typeof import('./src/components/oauth/olink.vue')['default']
    ReCaptcha: typeof import('./src/components/captcha/ReCaptcha.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/icons/setting.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    Translate: typeof import('./src/components/icons/translate.vue')['default']
    User: typeof import('./src/components/icons/user.vue')['default']
    Wallet: typeof import('./src/components/icons/home/wallet.vue')['default']
    World: typeof import('./src/components/icons/world.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
