FROM python:3.7

ENV PYTHONUNBUFFERED 1
ENV COMPOSE 1

MAINTAINER zmh-program

RUN mkdir /opt/Zh-Website
WORKDIR /opt/Zh-Website
ADD . /opt/Zh-Website

RUN apt-get update \
  && apt-get install ffmpeg libsm6 libxext6  -y

RUN  python3 -m pip install --upgrade pip \
  && pip3 install opencv-python-headless -i https://pypi.douban.com/simple/ \
  && pip3 install cryptography -i https://pypi.douban.com/simple/ \
  && pip3 install -r requirements.txt -i https://pypi.douban.com/simple/ \
  && python3 manage.py collectstatic --noinput
