# Generated by Django 3.2.16 on 2023-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='127.0.0.1', null=True),
        ),
    ]
