# Generated by Django 3.2.16 on 2022-11-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=12)),
                ('password', models.CharField(default='', max_length=32)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='', max_length=200)),
                ('identity', models.SmallIntegerField(choices=[(0, 'User'), (1, 'VIP'), (2, 'Admin'), (3, 'Server-Owner')])),
                ('user_bind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.user')),
            ],
        ),
    ]
