# Generated by Django 3.2.16 on 2022-12-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0002_adminiphistory_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iprequestanalysis',
            options={'verbose_name': 'IP Analysis'},
        ),
        migrations.AlterModelTable(
            name='iprequestanalysis',
            table='geoip',
        ),
        migrations.DeleteModel(
            name='AdminIPHistory',
        ),
    ]
