# Generated by Django 3.2.16 on 2023-01-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_id', models.PositiveIntegerField(default=0)),
                ('oauth_name', models.CharField(max_length=50)),
                ('oauth_app', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'OAuth',
                'db_table': 'oauth',
            },
        ),
    ]
