# Generated by Django 3.2.16 on 2022-11-27 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('path', models.FilePathField(default='/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user_bind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.user')),
            ],
        ),
    ]
