# Generated by Django 3.2.16 on 2022-11-27 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='name',
            new_name='real_name',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='path',
        ),
        migrations.AddField(
            model_name='userfile',
            name='uuid_name',
            field=models.UUIDField(default=uuid.UUID('90a597e4-7718-4bfc-a4ba-94fa61a4a54b')),
        ),
    ]
