# Generated by Django 3.2.16 on 2022-11-27 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
        ('files', '0002_auto_20221127_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='user_bind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.user'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='uuid_name',
            field=models.UUIDField(default=uuid.UUID('60e9f988-83c3-415d-9a1b-737f77390241')),
        ),
    ]
