# Generated by Django 3.2.16 on 2022-12-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_userfile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfile',
            options={'verbose_name': 'Files'},
        ),
        migrations.AlterModelTable(
            name='userfile',
            table='file',
        ),
    ]
