# Generated by Django 3.2.16 on 2022-12-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20221230_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfile',
            options={'verbose_name': 'File'},
        ),
    ]
