# Generated by Django 3.2.16 on 2022-11-27 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20221127_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='uuid_name',
            field=models.UUIDField(default=uuid.UUID('bed6bd93-22b0-4e5d-aaa4-6c836034aea4')),
        ),
    ]
