# Generated by Django 3.2.16 on 2022-11-29 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_userfile_uuid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='uuid_name',
            field=models.UUIDField(default=uuid.UUID('22c2f6ff-4a53-429e-93c9-8b7774dec88d')),
        ),
    ]
