# Generated by Django 3.2.16 on 2022-12-04 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20221201_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='user_bind',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userfile',
            name='uuid_name',
            field=models.UUIDField(default=uuid.UUID('301ae878-517d-4108-941b-6e561a60ddd3')),
        ),
    ]
