# Generated by Django 3.2.16 on 2022-12-05 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20221204_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='uuid_name',
            field=models.UUIDField(default=uuid.UUID('1c64eef0-7c27-4316-a6e5-6867ff47bfc8')),
        ),
    ]
