# Generated by Django 3.2.16 on 2022-12-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(default='Unknown', max_length=50),
        ),
    ]
