# Generated by Django 3.2.16 on 2022-12-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='detail',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='identity',
        ),
    ]
