# Generated by Django 3.2.16 on 2022-12-18 15:34

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221215_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='static/images/media/avatars/default.png', upload_to='static/images/media/avatars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='codepen',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitee',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='', max_length=25),
        ),
    ]
