# Generated by Django 3.2.16 on 2022-12-18 15:45

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221218_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='media/avatars/default.png', upload_to='media/avatars'),
        ),
    ]
