# Generated by Django 3.2.16 on 2022-12-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth',
        ),
    ]
